from tools.bq_mcp import query_response_metrics, search_emails_by_category, vector_search_emails
from tools.embedding_tool import generate_embedding
from tools.analytics_tool import get_response_time_analytics
from tools.gmail_mcp import send_analytics_email, get_contact_list
from db.mongo_client import get_collection
import json
import pandas as pd
from datetime import datetime, UTC

def generate_response_time_report(user_email: str, contact_emails: list):
    """
    Orchestrator: Generates response time analytics and emails the report to the user.
    """
    print(f"[*] Generating Response Time Report for {user_email} vs {contact_emails}...")
    
    analytics = get_response_time_analytics(user_email, contact_emails)
    if analytics["status"] == "error":
        return analytics["message"]
    
    # 1. Build HTML Body
    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif;">
        <h2 style="color: #4285F4;">Inbox Analytics: Response Time Report</h2>
        <p>This report analyzes your communication patterns with: <b>{', '.join(contact_emails)}</b></p>
        
        <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
            <h3>Global Averages</h3>
            <ul>
                <li><b>Recipient Avg Response Time:</b> {analytics['metrics']['recipient_avg']} hours</li>
                <li><b>Your Avg Response Time:</b> {analytics['metrics']['me_avg']} hours</li>
            </ul>
        </div>
    """
    
    for i, chart in enumerate(analytics["charts"]):
        html += f"""
        <div style="margin-bottom: 30px;">
            <h4>{chart['title']}</h4>
            <img src="cid:image{i}" style="max-width: 100%; border: 1px solid #ddd; border-radius: 4px;">
        </div>
        """
    
    html += """
        <p style="font-size: 12px; color: #777;">Generated by Gemini Inbox Analytics Agent.</p>
    </body>
    </html>
    """
    
    # 2. Send Email
    res = send_analytics_email(user_email, "[AGENT REPORT] Inbox Response Time Analytics", html, analytics["charts"])
    return res

def extract_keywords(note: str):
    """
    Heuristic to extract high-value keywords for Hybrid Search.
    Focuses on important terms like 'trigger', 'notification', 'alert'.
    """
    # Simple extraction: all words > 4 chars, plus some specific ones
    words = note.lower().replace(".", "").replace(",", "").split()
    high_value = {"trigger", "alert", "mail", "email", "test", "news"}
    keywords = [w for w in words if len(w) > 4 or w in high_value]
    # Limit to top 5 keywords for SQL performance
    return list(set(keywords))[:5]

def get_recommendations_for_action(user_email: str, action: str, threshold: float = 0.8):
    """
    Helper to find email candidates in BigQuery based on user preferences.
    Uses the dynamic threshold passed from the UI and Hybrid Search.
    """
    try:
        pref_collection = get_collection("UserPreferences")
        prefs = list(pref_collection.find({"user_id": user_email, "structured_rule.preferred_action": action}))
        
        all_candidates = []
        for p in prefs:
            note = p.get("llm_semantic_note")
            if not note: continue
            
            # Hybrid Search: Extract keywords to boost short/test messages
            keywords = extract_keywords(note)
            print(f"[*] Analyzing preference: '{note[:50]}...' (Keywords: {keywords})")
            
            embedding = generate_embedding(note)
            results_json = vector_search_emails(embedding, keywords=keywords)
            candidates = json.loads(results_json)
            
            # Debug: Log top 3 scores
            if candidates:
                top_scores = [round(c.get('similarity', 0), 3) for c in candidates[:3]]
                print(f"    - Top similarity scores found in BigQuery: {top_scores}")

            # Apply dynamic threshold
            filtered = [c for c in candidates if c.get("similarity", 0) > threshold]
            print(f"    - Found {len(filtered)} candidates above threshold {threshold}")
            all_candidates.extend(filtered)
            
        return all_candidates
    except Exception as e:
        print(f"Error getting {action} recommendations: {str(e)}")
        return []

def generate_tiered_recommendation_report(user_email: str, notify_tiering: bool = True, notify_unsubscribe: bool = True, similarity_threshold: float = 0.8):
    """
    Orchestrator: Generates recommendation report and emails it to the user.
    Respects UI preferences to skip specific tiers and applies dynamic thresholding.
    """
    print(f"[*] Generating Tiered Recommendation Report for {user_email} (Threshold: {similarity_threshold})...")
    
    unsubscribe = get_recommendations_for_action(user_email, "unsubscribe", similarity_threshold) if notify_unsubscribe else []
    archive = get_recommendations_for_action(user_email, "archive", similarity_threshold) if notify_tiering else []
    delete = get_recommendations_for_action(user_email, "delete", similarity_threshold) if notify_tiering else []
    
    # 1. Build HTML
    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif;">
        <h2 style="color: #DB4437;">Inbox Analytics: Optimization Recommendations</h2>
        <p>Based on your learned preferences, here are some recommendations to clean up your inbox.</p>
    """
    
    sections = [
        {"title": "Unsubscribe Recommendations", "items": unsubscribe},
        {"title": "Archive Recommendations", "items": archive},
        {"title": "Trash (Delete) Recommendations", "items": delete}
    ]
    
    for section in sections:
        html += f"<h3 style='border-bottom: 2px solid #eee; padding-bottom: 5px;'>{section['title']}</h3>"
        if not section["items"]:
            html += "<p><i>No recommendations found for this category.</i></p>"
        else:
            html += "<ul>"
            for item in section["items"][:5]:
                html += f"<li><b>{item['subject']}</b><br><small>From: {item['sender']} | Similarity: {round(item['similarity']*100, 1)}%</small></li>"
            html += "</ul>"
            
    html += """
        <br>
        <p style="font-size: 12px; color: #777;">Generated by Gemini Inbox Analytics Agent.</p>
    </body>
    </html>
    """
    
    # 2. Send Email
    res = send_analytics_email(user_email, "[AGENT REPORT] Inbox Optimization Recommendations", html)
    return res

# --- LEGACY WRAPPERS ---
def find_emails_for_unsubscribe(preferences_note: str = None):
    # Keep for compatibility if needed
    return {"status": "deprecated", "message": "Use generate_tiered_recommendation_report instead."}
